language: ruby
rvm:
  - "3.1.2"
cache: bundler

before_install:
  - "gem update --system 3.1.2"
  - "gem install bundler -v 2.3.7"

script: "bundle lock --add-platform x86_64-linux && bundle exec jekyll build"
