redirects:
  /en/glossary/serialized-block: https://developer.bitcoin.org/glossary
  /news: /version-history
  /clients: /choose-your-wallet
  /de/bitcoin-fuer-enthusiasten: /de/innovation

aliases:
  --author=Satoshi Nakamoto: Satoshi Nakamoto
  sebulino: Sebastian Alscher
  derschulze: Stefan Schulz
  lan: Lan Mai

title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/"
url: "http://127.0.0.1:4002/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sebulino
github_username:  sebulino

source: .
destination: ./_site
plugins_dir: ./_plugins
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - vendor  # Travis CI creates a vendor/ dir with files we shouldn't render
  - .idea
include:
  - _pages


future:      true
lsi:         false
markdown:    kramdown
permalink:   date
excerpt_separator: "<!-- END_EXCERPT -->"

rdiscount:
  extensions: []

markdown: kramdown
kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  enable_coderay: false
  syntax_highlighter: rouge

collections:
  ## _alerts
  alerts:
    output: true
    permalink: /alert/:path
  ## _devdocs
  devdocs:
    output: false

donation_banner:
  address: 3E8ociqZa9mZUSwGdSmAEMAoAxBK3FNDcd
  display: true
  amounts_in_usd:
    - 5
    - 25
    - 50

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.
      layout: "page"
  - scope:
      path: ""
      type: alerts
    values:
      layout: alert
      lang: de
  - scope:
      path: ""
      type: posts
    values:
      lang: de

## Options as of version 3.4.20 are: nested (default), compact, compressed, or expanded
sass:
  style: compressed
